---
title: "COVID-19 Final Capstone"
author: "Ciara Moore, Daijiro Yokota, Christina Cai"
date: "4/20/2020"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r, warning=FALSE, message=FALSE}
## tsiR examples

## load the package and dependencies
## kernlab is for the gaussian process 
## the rest are for plotting 
require(tsiR)
require(kernlab)
require(ggplot2)
require(reshape2)
require(grid)
require(dplyr)
require(xts)
library(lubridate)
library(janitor)
library(ggExtra)
library(rstan)
library(ggExtra)
```

# our data
```{r}
load("covid.Rda")
covid <- data
covid$pop <- covid$population
covid$time <- covid$date
covid$cases <- covid$confirmed
covid$births <- covid$BirthRate * covid$population/1000  
```




```{r}
server1 <- function(input, output) {
  
  df_country <- covid %>% 
    filter(country == input$Country) %>% 
    select(pop, time, births, cases)
  
  df_weekly <- df_country %>%
    group_by(time = week(time)) %>% 
    summarise(births = mean(births),
            pop = mean(pop),
            cases = sum(cases)) %>%
    filter(time!=18)
  
  df_countryParms <- estpars(data=df_weekly,IP=1,
                          alpha=0.97, sbar=NULL,
                          regtype='loess',
                          family='gaussian',link='identity')  
  
  plotbreaks(data=df_weekly,threshold=3)
  
  df_countryRes <- simulatetsir(data=df_weekly,IP=1,
                             parms=df_countryParms,
                             epidemics='break',threshold=4,
                             method='pois',nsim=100)
  
  output$simulation <- renderPlot(
    plotcomp(sim = df_countryRes))
}

# Build the user interface
ui1 <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      h4("Specify the country:"), 
      selectInput("Country", "", list("China", "Italy", "Spain", "US"))
    ),
    
    mainPanel(
      h4("Plot of the simulation:"), 
      plotOutput("simulation")
    )
  )
)
```


````{r warning=FALSE}
# Run the shiny app!
shinyApp(ui = ui1, server = server1)
```

